---

- name: Make a copy of current img
  copy:
    dest: "/vagrant/img/rpi-{{ img_mount.id | mandatory }}-{{ img_mount.image }}"
    remote_src: yes
    src: "/vagrant/img/{{ img_mount.image }}"

- name: Ensure scripts
  copy:
    dest: "/tmp/mount_img"
    mode: u+x,g+x,o+x
    src: mount_img

- name: Mount boot and main partition
  become: yes
  command: "/tmp/mount_img /vagrant/img/rpi-{{ img_mount.id | mandatory }}-{{ img_mount.image }}"
  args:
    creates: /mnt/rpi-a8af184/main
