---

- name:
  assert:
    that:
      - img_mount.id is defined

- name: Ensure scripts
  copy:
    dest: "/tmp/mount_img"
    mode: u+x,g+x,o+x
    src: mount_img

- include: mount.yml
  when: img_mount.mounted

- include: umount.yml
  when: not img_mount.mounted
