---

- name: Build Rapberypi SD Card Image
  hosts: "{{ hosts }}"

  roles:
    - role: img_mount
      img_mount:
        id: "{{ image_id }}"

    - role: raspbian_headless
      raspbian_headless:
        id: "{{ image_id }}"
